apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - keycloak-ingress.yaml
  - ingress-tls.sealedsecret.yaml
  - public-access.yaml
  - networkpolicy.yaml

patches:
  - path: postgres.vault-patch.yaml
  - path: keycloak.vault-patch.yaml
  - path: keycloak-client-sync.vault-patch.yaml
  - path: keycloak.public-url-patch.yaml
