apiVersion: v1
kind: Service
metadata:
  name: keycloak-public
spec:
  type: ExternalName
  externalName: traefik.kube-system.svc.cluster.local
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
