apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Prod shared infrastructure managed by Argo CD
  sourceRepos:
    - https://github.com/DongHyeonka/Project-Auth-GitOps
    - https://bitnami-labs.github.io/sealed-secrets
  destinations:
    - namespace: platform-prod
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRole
    - group: "rbac.authorization.k8s.io"
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: ""
      kind: PersistentVolumeClaim
    - group: "bitnami.com"
      kind: SealedSecret
    - group: "rbac.authorization.k8s.io"
      kind: Role
    - group: "rbac.authorization.k8s.io"
      kind: RoleBinding
    - group: "apps"
      kind: Deployment
    - group: "apps"
      kind: StatefulSet
    - group: "apps"
      kind: ReplicaSet
    - group: "autoscaling"
      kind: HorizontalPodAutoscaler
    - group: "batch"
      kind: Job
    - group: "networking.k8s.io"
      kind: Ingress
    - group: "policy"
      kind: PodDisruptionBudget
  orphanedResources:
    warn: true
