apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: api-dev

resources:
  - ../../base
  - namespace.yaml
  - configmap.yaml
  - ingress.yaml
  - public-access.yaml
  - networkpolicy.yaml
  - ghcr-regcred.sealedsecret.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
  - name: ghcr.io/donghyeonka/project-api-server
    newName: ghcr.io/donghyeonka/project-api-server
    newTag: fd097c9
