apiVersion: v1
kind: Service
metadata:
  name: api-public
spec:
  type: ExternalName
  externalName: traefik.kube-system.svc.cluster.local
  ports:
    - name: http
      port: 80
      targetPort: 80
