apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: auth-dev

resources:
- ../../base
- namespace.yaml
- configmap.yaml
- ingress.yaml
- public-access.yaml
- networkpolicy.yaml
- ghcr-regcred.sealedsecret.yaml

patches:
- path: deployment.vault-patch.yaml
- path: db-migration-job.vault-patch.yaml

generatorOptions:
  disableNameSuffixHash: true

images:
- name: ghcr.io/donghyeonka/project-auth-server
  newName: ghcr.io/donghyeonka/project-auth-server
  newTag: 64b4e78
