apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-db-migration
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-2"
automountServiceAccountToken: false
imagePullSecrets:
  - name: ghcr-regcred
